### ISSUE TITLE
我使用您公开权重在加载过程中出现缺失信息，您这边可以提供一下环境的requirements.txt和运行代码的README.md吗

### ISSUE THREAD

**Issue by yanyide123** [jiazhou-garland/MLEEP#1]
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MLEEP:
        Missing key(s) in state_dict: "SE_block.fc.0.weight", "SE_block.fc.2.weight", "ECE_block.linear_transfer.weight", "ECE_block.linear_transfer.bias", "ECE_block.query.weight", "ECE_block.query.bias", "ECE_block.g.0.weight", "EC
E_block.g.0.bias", "ECE_block.g.1.weight", "ECE_block.g.1.bias", "ECE_block.g.1.running_mean", "ECE_block.g.1.running_var".
        Unexpected key(s) in state_dict: "se.fc.0.weight", "se.fc.2.weight", "channel_similarity.linear_transfer.weight", "channel_similarity.linear_transfer.bias", "channel_similarity.query.weight", "channel_similarity.query.bias",
"channel_similarity.g.0.weight", "channel_similarity.g.0.bias", "channel_similarity.g.1.weight", "channel_similarity.g.1.bias", "channel_similarity.g.1.running_mean", "channel_similarity.g.1.running_var", "channel_similarity.g.1.num_
batches_tracked"

**Comment by jiazhou-garland** [comment]
您好，这是我硕士期间在电子科大的工作，目前已硕士毕业不做这个方向了，相关环境和权重备份在原实验室。您可联系[张萍教授](https://faculty.uestc.edu.cn/zhangping/zh_CN/index.htm)咨询相关问题。

另：权重公开了max-input和multi-input两个版本，对应模型版本不同，上述问题很大可能是权重与模型版本没对应。
